In [10]:
import pandas as pd

jan = pd.DataFrame({
    "Order_ID": ["O101","O102"],
    "Revenue": [1200,800]
})

feb = pd.DataFrame({
    "Order_ID": ["O103","O104"],
    "Revenue": [2100,600]
})

combined=pd.concat([jan,feb],axis=0)#rows
print(combined)
combined=pd.concat([jan,feb],axis=1)#columns
print(f"combined {combined}")
a=pd.DataFrame({"class":['1st','2nd']})
b=pd.DataFrame({"roll_no":[66,99,90,92]})
com=pd.concat([a,b])
print(com)
b=pd.DataFrame({"roll_no":[66,99,90,92],"sec":['a','b','c','d']})

com=pd.concat([a,b],axis=1)
print(com)
sales = pd.DataFrame({
    "Order_ID": ["O101","O102","O103","O104",'0105'],
    "Customer_ID": ["C01","C02","C01","C04",'c06'],
    "Product_ID": ["P01","P02","P03","P01",'p01'],
    "Quantity": [2,1,3,1,5],
    "Revenue": [1200,800,2100,600,3000]
})

customers = pd.DataFrame({
    "Customer_ID": ["C01","C02","C03","C04","C05"],
    "Customer_Name": ["Arun","Priya","Rahul","Sneha","pranay"],
    "City": ["Hyderabad","Chennai","Bengaluru","Hyderabad","Hyderabad"],
    "Segment": ["Retail","Corporate","Retail","Corporate","Delliote"]
})

products = pd.DataFrame({
    "Product_ID": ["P01","P02","P03"],
    "Product": ["Laptop","Monitor","Phone"],
    "Category": ["Electronics","Electronics","Mobile"]
})
mer=pd.merge(sales,customers,on="Customer_ID",how='left')
print(mer)
# print(customers)
mer=pd.merge(sales,customers,on="Customer_ID",how='right')
print(mer)

  Order_ID  Revenue
0     O101     1200
1     O102      800
0     O103     2100
1     O104      600
combined   Order_ID  Revenue Order_ID  Revenue
0     O101     1200     O103     2100
1     O102      800     O104      600
  class  roll_no
0   1st      NaN
1   2nd      NaN
0   NaN     66.0
1   NaN     99.0
2   NaN     90.0
3   NaN     92.0
  class  roll_no sec
0   1st       66   a
1   2nd       99   b
2   NaN       90   c
3   NaN       92   d
  Order_ID Customer_ID Product_ID  Quantity  Revenue Customer_Name       City  \
0     O101         C01        P01         2     1200          Arun  Hyderabad
1     O102         C02        P02         1      800         Priya    Chennai
2     O103         C01        P03         3     2100          Arun  Hyderabad
3     O104         C04        P01         1      600         Sneha  Hyderabad
4     0105         c06        p01         5     3000           NaN        NaN

     Segment
0     Retail
1  Corporate
2     Retail
3  Corporate
4        NaN
  Order_ID Customer_ID Product_ID  Quantity  Revenue Customer_Name       City  \
0     O101         C01        P01       2.0   1200.0          Arun  Hyderabad
1     O103         C01        P03       3.0   2100.0          Arun  Hyderabad
2     O102         C02        P02       1.0    800.0         Priya    Chennai
3      NaN         C03        NaN       NaN      NaN         Rahul  Bengaluru
4     O104         C04        P01       1.0    600.0         Sneha  Hyderabad
5      NaN         C05        NaN       NaN      NaN        pranay  Hyderabad

     Segment
0     Retail
1     Retail
2  Corporate
3     Retail
4  Corporate
5   Delliote

In [4]:
mer=pd.merge(sales,customers,on="Customer_ID",how='left')
mer

,Order_ID,Customer_ID,Product_ID,Quantity,Revenue,Customer_Name,City,Segment
0,O101,C01,P01,2,1200,Arun,Hyderabad,Retail
1,O102,C02,P02,1,800,Priya,Chennai,Corporate
2,O103,C01,P03,3,2100,Arun,Hyderabad,Retail
3,O104,C04,P01,1,600,Sneha,Hyderabad,Corporate
4,0105,c06,p01,5,3000,NaN,NaN,NaN

In [5]:
customers

  Customer_ID Customer_Name       City    Segment
0         C01          Arun  Hyderabad     Retail
1         C02         Priya    Chennai  Corporate
2         C03         Rahul  Bengaluru     Retail
3         C04         Sneha  Hyderabad  Corporate
4         C05        pranay  Hyderabad   Delliote

In [6]:
sales

  Order_ID Customer_ID Product_ID  Quantity  Revenue
0     O101         C01        P01         2     1200
1     O102         C02        P02         1      800
2     O103         C01        P03         3     2100
3     O104         C04        P01         1      600
4     0105         c06        p01         5     3000

In [7]:
mer=pd.merge(sales,customers,on="Customer_ID",how='left')
mer

,Order_ID,Customer_ID,Product_ID,Quantity,Revenue,Customer_Name,City,Segment
0,O101,C01,P01,2,1200,Arun,Hyderabad,Retail
1,O102,C02,P02,1,800,Priya,Chennai,Corporate
2,O103,C01,P03,3,2100,Arun,Hyderabad,Retail
3,O104,C04,P01,1,600,Sneha,Hyderabad,Corporate
4,0105,c06,p01,5,3000,NaN,NaN,NaN

In [8]:
mer=pd.merge(sales,customers,on="Customer_ID",how='right')
mer

,Order_ID,Customer_ID,Product_ID,Quantity,Revenue,Customer_Name,City,Segment
0,O101,C01,P01,2.0,1200.0,Arun,Hyderabad,Retail
1,O103,C01,P03,3.0,2100.0,Arun,Hyderabad,Retail
2,O102,C02,P02,1.0,800.0,Priya,Chennai,Corporate
3,NaN,C03,NaN,NaN,NaN,Rahul,Bengaluru,Retail
4,O104,C04,P01,1.0,600.0,Sneha,Hyderabad,Corporate
5,NaN,C05,NaN,NaN,NaN,pranay,Hyderabad,Delliote

In [12]:
sales = pd.DataFrame({
    "Order_ID": ["O101","O102","O103","O104",'0105'],
    "Customer_ID": ["C01","C02","C01","C04",'c06'],
    "Product_ID": ["P01","P02","P03","P01",'p01'],
    "Quantity": [2,1,3,1,5],
    "Revenue": [1200,800,2100,600,3000]
})

customers = pd.DataFrame({
    "ID": ["C01","C02","C03","C04","C05"],
    "Customer_Name": ["Arun","Priya","Rahul","Sneha","pranay"],
    "City": ["Hyderabad","Chennai","Bengaluru","Hyderabad","Hyderabad"],
    "Segment": ["Retail","Corporate","Retail","Corporate","Delliote"]
})

In [13]:
sales
customers

    ID Customer_Name       City    Segment
0  C01          Arun  Hyderabad     Retail
1  C02         Priya    Chennai  Corporate
2  C03         Rahul  Bengaluru     Retail
3  C04         Sneha  Hyderabad  Corporate
4  C05        pranay  Hyderabad   Delliote

In [14]:
sales

  Order_ID Customer_ID Product_ID  Quantity  Revenue
0     O101         C01        P01         2     1200
1     O102         C02        P02         1      800
2     O103         C01        P03         3     2100
3     O104         C04        P01         1      600
4     0105         c06        p01         5     3000

In [19]:
merged=pd.merge(sales,customers,left_on="Customer_ID",right_on="ID",how='left')
merged

,Order_ID,Customer_ID,Product_ID,Quantity,Revenue,ID,Customer_Name,City,Segment
0,O101,C01,P01,2,1200,C01,Arun,Hyderabad,Retail
1,O102,C02,P02,1,800,C02,Priya,Chennai,Corporate
2,O103,C01,P03,3,2100,C01,Arun,Hyderabad,Retail
3,O104,C04,P01,1,600,C04,Sneha,Hyderabad,Corporate
4,0105,c06,p01,5,3000,NaN,NaN,NaN,NaN

In [20]:
merged=pd.merge(sales,customers,left_on="Customer_ID",right_on="ID",how='right')
merged

,Order_ID,Customer_ID,Product_ID,Quantity,Revenue,ID,Customer_Name,City,Segment
0,O101,C01,P01,2.0,1200.0,C01,Arun,Hyderabad,Retail
1,O103,C01,P03,3.0,2100.0,C01,Arun,Hyderabad,Retail
2,O102,C02,P02,1.0,800.0,C02,Priya,Chennai,Corporate
3,NaN,NaN,NaN,NaN,NaN,C03,Rahul,Bengaluru,Retail
4,O104,C04,P01,1.0,600.0,C04,Sneha,Hyderabad,Corporate
5,NaN,NaN,NaN,NaN,NaN,C05,pranay,Hyderabad,Delliote

In [21]:
merged=pd.merge(sales,customers,left_on="Customer_ID",right_on="ID",how='inner')
merged

,Order_ID,Customer_ID,Product_ID,Quantity,Revenue,ID,Customer_Name,City,Segment
0,O101,C01,P01,2,1200,C01,Arun,Hyderabad,Retail
1,O102,C02,P02,1,800,C02,Priya,Chennai,Corporate
2,O103,C01,P03,3,2100,C01,Arun,Hyderabad,Retail
3,O104,C04,P01,1,600,C04,Sneha,Hyderabad,Corporate

In [22]:
merged=pd.merge(sales,customers,left_on="Customer_ID",right_on="ID",how='outer')
merged

,Order_ID,Customer_ID,Product_ID,Quantity,Revenue,ID,Customer_Name,City,Segment
0,O101,C01,P01,2.0,1200.0,C01,Arun,Hyderabad,Retail
1,O103,C01,P03,3.0,2100.0,C01,Arun,Hyderabad,Retail
2,O102,C02,P02,1.0,800.0,C02,Priya,Chennai,Corporate
3,NaN,NaN,NaN,NaN,NaN,C03,Rahul,Bengaluru,Retail
4,O104,C04,P01,1.0,600.0,C04,Sneha,Hyderabad,Corporate
5,NaN,NaN,NaN,NaN,NaN,C05,pranay,Hyderabad,Delliote
6,0105,c06,p01,5.0,3000.0,NaN,NaN,NaN,NaN

In [23]:
merged=pd.merge(sales,customers,left_on="Customer_ID",right_on="ID",how='outer',indicator=True)
merged

,Order_ID,Customer_ID,Product_ID,Quantity,Revenue,ID,Customer_Name,City,Segment,_merge
0,O101,C01,P01,2.0,1200.0,C01,Arun,Hyderabad,Retail,both
1,O103,C01,P03,3.0,2100.0,C01,Arun,Hyderabad,Retail,both
2,O102,C02,P02,1.0,800.0,C02,Priya,Chennai,Corporate,both
3,NaN,NaN,NaN,NaN,NaN,C03,Rahul,Bengaluru,Retail,right_only
4,O104,C04,P01,1.0,600.0,C04,Sneha,Hyderabad,Corporate,both
5,NaN,NaN,NaN,NaN,NaN,C05,pranay,Hyderabad,Delliote,right_only
6,0105,c06,p01,5.0,3000.0,NaN,NaN,NaN,NaN,left_only

In [25]:
merged=pd.merge(sales,customers,left_on="Customer_ID",right_on="ID",how='outer',indicator=True,validate="many_to_one")
merged

,Order_ID,Customer_ID,Product_ID,Quantity,Revenue,ID,Customer_Name,City,Segment,_merge
0,O101,C01,P01,2.0,1200.0,C01,Arun,Hyderabad,Retail,both
1,O103,C01,P03,3.0,2100.0,C01,Arun,Hyderabad,Retail,both
2,O102,C02,P02,1.0,800.0,C02,Priya,Chennai,Corporate,both
3,NaN,NaN,NaN,NaN,NaN,C03,Rahul,Bengaluru,Retail,right_only
4,O104,C04,P01,1.0,600.0,C04,Sneha,Hyderabad,Corporate,both
5,NaN,NaN,NaN,NaN,NaN,C05,pranay,Hyderabad,Delliote,right_only
6,0105,c06,p01,5.0,3000.0,NaN,NaN,NaN,NaN,left_only

In [26]:
left = pd.DataFrame({
    "ID":["A","A"],
    "Value1":[10,20]
})

right = pd.DataFrame({
    "ID":["A","A"],
    "Value2":[100,200]
})

result = pd.merge(
    left, right, on="ID"
)

result

  ID  Value1  Value2
0  A      10     100
1  A      10     200
2  A      20     100
3  A      20     200

In [27]:
a = pd.DataFrame({
    "Customer_ID":["C01"],
    "Status":["Active"]
})

b = pd.DataFrame({
    "Customer_ID":["C01"],
    "Status":["VIP"]
})

result = pd.merge(
    a, b,
    on="Customer_ID",
    suffixes=("_customer","_crm")
)

result

  Customer_ID Status_customer Status_crm
0         C01          Active        VIP